# Breaks reusing MD snippets extracted to files
first-line-heading: false

# Allow HTML span elements to set font sizes
no-inline-html:
  allowed_elements:
    - span

# FIXME: Enable these, fix errors
line-length: false
code-block-style: false
blanks-around-fences: false
blanks-around-lists: false
no-trailing-spaces: false
fenced-code-language: false
ul-style: false
blanks-around-headings: false
commands-show-output: false
