# Breaks reusing MD snippets extracted to files
first-line-heading: false

# Allow HTML span elements to set font sizes
no-inline-html:
  allowed_elements:
    - span

# FIXME: Enable these, fix errors
line-length: false
