---
name: YAML Linting
on: pull_request

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    name: YAML Linting
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v1
        with:
          file_or_dir: .
          config_file: .yamllint.yml
